/*

 KNIGHT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 16

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define knightBank 0

/* Super Gameboy palette 0 */
#define knightSGBPal0c0 6076
#define knightSGBPal0c1 8935
#define knightSGBPal0c2 6596
#define knightSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define knightSGBPal1c0 6076
#define knightSGBPal1c1 8935
#define knightSGBPal1c2 6596
#define knightSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define knightSGBPal2c0 6076
#define knightSGBPal2c1 8935
#define knightSGBPal2c2 6596
#define knightSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define knightSGBPal3c0 6076
#define knightSGBPal3c1 8935
#define knightSGBPal3c2 6596
#define knightSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define knightCGBPal0c0 6076
#define knightCGBPal0c1 8935
#define knightCGBPal0c2 6596
#define knightCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define knightCGBPal1c0 15317
#define knightCGBPal1c1 31638
#define knightCGBPal1c2 32022
#define knightCGBPal1c3 11281

/* Gameboy Color palette 2 */
#define knightCGBPal2c0 21374
#define knightCGBPal2c1 18112
#define knightCGBPal2c2 11553
#define knightCGBPal2c3 7203

/* Gameboy Color palette 3 */
#define knightCGBPal3c0 6076
#define knightCGBPal3c1 8935
#define knightCGBPal3c2 6596
#define knightCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define knightCGBPal4c0 6076
#define knightCGBPal4c1 8935
#define knightCGBPal4c2 6596
#define knightCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define knightCGBPal5c0 6076
#define knightCGBPal5c1 8935
#define knightCGBPal5c2 6596
#define knightCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define knightCGBPal6c0 6076
#define knightCGBPal6c1 8935
#define knightCGBPal6c2 6596
#define knightCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define knightCGBPal7c0 6076
#define knightCGBPal7c1 8935
#define knightCGBPal7c2 6596
#define knightCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char knightCGB[];
/* Start of tile array. */
extern unsigned char knight[];

/* End of KNIGHT.H */
